name: CI Angular
on: push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install the shit
        run: npm ci
      - name: Run tests
        run: ng test --no-watch --code-coverage --browsers=ChromeHeadlessCI
